services:
  db:
    image: postgres:16-alpine
    container_name: budget_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: budget1234
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes:
      - budget_pgdata:/var/lib/postgresql/data

volumes:
  budget_pgdata:
